SG-34315 - Rebranding
shotgunsoftware/tk-vred pull request #107
Opened 2024-02-07 11:29 UTC by juanburgosautoglb

Change all the shotgrid/shotgun occurrences in the repository.

2024-02-23 18:41 UTC, julien-lang requested changes
A few things to change.

Also, I still see one reference to ShotGrid in hooks/tk-multi-publish2/basic/publish_session.py

And what about the plugins/Shotgun/vred_shotgun_menu.gif asset? @staceyoue could you help us with that please?

2024-02-23 18:41 UTC, julien-lang commented on engine.py
> +    """A VRED engine for Flow Production Tracking."""
```suggestion
    """A VRED engine for Flow Production Tracking Toolkit."""
```

2024-02-23 18:41 UTC, julien-lang commented on engine.py
> +                "The Flow Production Tracking has not yet been fully tested "
```suggestion
                "The Flow Production Tracking Toolkit has not yet been fully tested "
```

2024-02-23 18:41 UTC, julien-lang commented on engine.py
> +                    "Warning - Flow Production Tracking!",
```suggestion
                    "Warning - Flow Production Tracking Toolkit!",
```

2024-02-23 18:41 UTC, julien-lang commented on engine.py
> +                "The Flow Production Tracking is not fully capable with VRED {version}. "
```suggestion
                "The Flow Production Tracking Toolkit is not fully capable with VRED {version}. "
```

2024-02-23 18:41 UTC, julien-lang commented on engine.py
> +                    "Warning - Flow Production Tracking!",
```suggestion
                    "Warning - Flow Production Tracking Toolkit!",
```

2024-02-26 18:47 UTC, staceyoue commented
> And what about the plugins/Shotgun/vred_shotgun_menu.gif asset? @staceyoue could you help us with that please?

@julien-lang I created this PR to remove obsolete code that used to display the gif - we no longer show that gif, so it will be removed.

2024-02-28 19:04 UTC, staceyoue requested changes
To change the "ShotGrid" menu name, you will need to update the text here:
https://github.com/shotgunsoftware/tk-vred/blob/95d8637fa2ddca08f7dd0479fb7b872b201e9e56/python/tk_vred/menu_generation.py#L23

2024-02-28 19:31 UTC, julien-lang approved these changes
LGTM!

2024-02-28 20:17 UTC, staceyoue approved these changes
Awesome!

2024-03-20 20:37 UTC, merged