SHOT-3496: VRED Refactor
shotgunsoftware/tk-vred pull request #40
Opened 2020-08-24 14:56 UTC by staceyoue

- [SHOT-3388] Remove operations.py and move methods into engine and/or hook
- [SHOT-3505] Refactor Shotgun menu generation in VRED
- [SHOT-3373] Remove publish plugin for geometry and related methods
- [SHOT-3501] Hide "Jump to file system" when the context has no filesystem

2020-08-24 15:02 UTC, staceyoue commented on python/tk_vred/__init__.py
> +from .menu_generation import VREDMenuGenerator
@rob-aitchison -- is there a way to define this without Hound complaining about it, or is this OK?

2020-08-24 15:14 UTC, rob-aitchison commented on python/tk_vred/__init__.py
> +from .menu_generation import VREDMenuGenerator
Hey @staceyoue , it looks like the combination of .hound.yml and .flake8 files can fix this; I looked at https://github.com/shotgunsoftware/tk-core to deduce this. :)

2020-08-24 15:27 UTC, staceyoue commented on python/tk_vred/__init__.py
> +from .menu_generation import VREDMenuGenerator
This seems to have resolved the issue -- thanks!

2020-08-25 16:46 UTC, rob-aitchison submitted a review, later dismissed
Looks great, thanks!

2020-09-01 10:19 UTC, barbara-darkshot requested changes
hey @staceyoue , I've attached some comments to the code review. Some of them are little changes and others are more thoughts :-)

2020-09-01 10:19 UTC, barbara-darkshot commented on hooks/tk-multi-workfiles2/basic/scene_operation.py
> +        engine.logger.debug(
same here for the hook logger instead of the engine's

2020-09-09 09:52 UTC, barbara-darkshot approved these changes
LGTM!

2020-09-09 12:28 UTC, rob-aitchison approved these changes
Looks good!

2020-09-09 12:56 UTC, merged